### ISSUE TITLE
next.js 1.2.3 Cannot find module 'find-up'

### ISSUE THREAD

**Issue by drwpow** [mars/heroku-nextjs-build#1]
First off, just want to say thank you to making this repo—this was a huge timesaver! I really appreciate the effort.

If you have time, I had a build problem when I upgraded next.js from 1.2 to 1.2.3. I got this build error on Heroku:

```
       [4/4] Building fresh packages...
       $ heroku-nextjs-build
       
       > myherokuappname@1.0.0 build /app/nextjs
       > next build
       
       { Error: Cannot find module 'find-up'
       @ multi bundles/pages/index.js
```

Pretty sure this has to do with [#319](https://github.com/zeit/next.js/issues/319) and the changes to how next handles glamor. Glamor is the dependency that has some kind of `find-up` mismatch: https://github.com/threepointone/glamor/blob/master/yarn.lock#L2344.

Anyway, opening up an issue here because I don’t have any problems building on my local machine; just Heroku. Are you seeing the same / have any pointers on how to troubleshoot this? Thanks!

**Comment by drwpow** [comment]
Update: so adding `find-up` as a dependency manually fixes the build on Heroku. At least for now.
